pub const CRYPTOSUITE_SIGN: &str = "bbs-termwise-signature-2023";
pub const CRYPTOSUITE_BOUND_SIGN: &str = "bbs-termwise-bound-signature-2023";
pub const CRYPTOSUITE_PROOF: &str = "bbs-termwise-proof-2023";
pub const NYM_IRI_PREFIX: &str = "urn:nym:";
pub const GENERATOR_SEED: &[u8; 28] = b"BBS_*_MESSAGE_GENERATOR_SEED"; // TODO: fix it later
pub const MAP_TO_SCALAR_AS_HASH_DST: &[u8; 32] = b"BBS_*_MAP_MSG_TO_SCALAR_AS_HASH_"; // TODO: fix it later
pub const DELIMITER: &[u8; 13] = b"__DELIMITER__"; // TODO: fix it later
pub const BLIND_SIG_REQUEST_CONTEXT: &[u8; 23] = b"BBS_*_BLIND_SIG_REQUEST"; // TODO: fix it later
pub const PPID_SEED: &[u8; 15] = b"BBS_*_PPID_SEED"; // TODO: fix it later
pub const PPID_PREFIX: &str = "https://zkp-ld.org/.well-known/genid/"; // TODO: fix it later
pub const TIMESTAMP_OFFSET: i64 = 62167219200; // Offset to set the timestamp `0000-01-01T00:00:00Z` to `0_i64`
pub const INTEGER32_OFFSET: i64 = 2147483648; // Offset to set the negative integer `-2^31` to `0_i64`
